#!/bin/bash

TOKEN="155092a434e8a3b1f4212b12d0cb3c13"
USER_ID="20"
OLD_PW="yummy"
NEW_PW="yummy2"

BASE_URL="http://tic-tac-toe.wdibos.com/"
URL="${BASE_URL}/change-password/${USER_ID}"

url() {

  CONTENT_TYPE="application/x-www-form-urlencoded"

  curl ${URL} \
  --include \
  --request PATCH \
  --header "Content-Type: ${CONTENT_TYPE}" \
  --header "Authorization: Token token=${TOKEN}" \
  --data-urlencode "password[old]=${OLD_PW}" \
  --data-urlencode "password[new]=${NEW_PW}"

}

#json() {

#  --header "Authorization: Token token=${TOKEN}" \

#}

#json

url

# data output from curl doesn't have a trailing newline
echo
